version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=supersecret
      - OLLAMA_MODEL=phi3
    volumes:
      - ./backend/appointments.db:/app/appointments.db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
